### PR TITLE
Update the INSTALL doc to detail how to get a full local index running.

### PR DESCRIPTION
**Pull request by higs4281**
This is strictly a documentation update, to give developers a way to get fully indexed CCDB data running locally.

### CODE REVIEW

**Review by willbarton — APPROVED** [review]
Reads well to me! I haven't tried it though to know if it works.

**Review by flacoman91 — APPROVED** [review]
This is good, and worked for me.  thanks

**Comment by higs4281** [comment]
After working with flacoman91, I can see the advantage of having two options rather than one opinionated one. 

It would be really nice to have one way to set up, but that would be at the expense of one group or the other.

**Comment by higs4281** [comment]
Also added sections on Elasticsearch2 and the production pipeline.

**Pull request merged**
